export const TYPE = 'SELECTTYPE/TYPE' as const;
export const SOCIALTYPE = 'SELECTTYPE/SOCIALTYPE' as const;
export const AREA = 'SELECTTYPE/AREA' as const;
export const GRADUATION = 'SELECTTYPE/GRADUATION' as const;
export const GRADUATION_YEAR = 'SELECTTYPE/GRADUATION_YEAR' as const;
export const GRADUATION_MONTH = 'SELECTTYPE/GRADUATION_MONTH' as const;
export const REMARK = 'SELECTTYPE/REMARK' as const;

export const SELECTTYPE = 'SELECTTYPE/SELECTTYPE' as const;
export const SELECTTYPE_SUCCESS = 'SELECTTYPE/SELECTTYPE_SUCCESS' as const;
export const SELECTTYPE_FAILURE = 'SELECTTYPE/SELECTTYPE_FAILURE' as const;

export const AUTOSAVE_SELECTTYPE = 'SELECTTYPE/AUTOSAVE_SELECTTYPE' as const;
export const AUTOSAVE_SELECTTYPE_SUCCESS = 'SELECTTYPE/AUTOSAVE_SELECTTYPE_SUCCESS' as const;
export const AUTOSAVE_SELECTTYPE_FAILURE = 'SELECTTYPE/AUTOSAVE_SELECTTYPE_FAILURE' as const;

export const GET_SELECTTYPE = 'SELECTTYPE/GET_SELECTTYPE' as const;
export const GET_SELECTTYPE_SUCCESS = 'SELECTTYPE/GET_SELECTTYPE_SUCCESS' as const;
export const GET_SELECTTYPE_FAILURE = 'SELECTTYPE/GET_SELECTTYPE_FAILURE' as const;
