export const INPUT = 'INFORMATION/INPUT' as const;
export const SEX = 'INFORMATION/SEX' as const;
export const BIRTHYEAR = 'INFORMATION/BIRTHYEAR' as const;
export const BIRTHMONTH = 'INFORMATION/BIRTHMONTH' as const;
export const BIRTHDATE = 'INFORMATION/BIRTHDATE' as const;
export const PICTUREURL = 'INFORMATION/PICTUREURL' as const;
export const SCHOOLCODE = 'INFORMATION/SCHOOLCODE' as const;
export const ADDRESS_AND_CODE = 'INFORMATION/ADDRESS_AND_CODE' as const;
export const SCHOOL_NAME = 'INFORMATION/SCHOOL_NAME' as const;

export const INFORMATION = 'INFORMATION/INFORMATION' as const;
export const INFORMATION_SUCCESS = 'INFORMATION/INFORMATION_SUCCESS' as const;
export const INFORMATION_FAILURE = 'INFORMATION/INFORMATION_FAILURE' as const;

export const GRADUATE_INFORMATION = 'INFORMATION/GRADUATE_INFORMATION' as const;
export const GRADUATE_INFORMATION_SUCCESS = 'INFORMATION/GRADUATE_INFORMATION_SUCCESS' as const;
export const GRADUATE_INFORMATION_FAILURE = 'INFORMATION/GRADUATE_INFORMATION_FAILURE' as const;

export const GET_INFORMATION = 'INFORMATION/GET_INFORMATION' as const;
export const GET_INFORMATION_SUCCESS = 'INFORMATION/GET_INFORMATION_SUCCESS' as const;
export const GET_INFORMATION_FAILURE = 'INFORMATION/GET_INFORMATION_FAILURE' as const;

export const GET_GRADUATE_INFORMATION = 'INFORMATION/GET_GRADUATE_INFORMATION' as const;
export const GET_GRADUATE_INFORMATION_SUCCESS = 'INFORMATION/GET_GRADUATE_INFORMATION_SUCCESS' as const;
export const GET_GRADUATE_INFORMATION_FAILURE = 'INFORMATION/GET_GRADUATE_INFORMATION_FAILURE' as const;

export const USER_PICTURE = 'INFORMATION/USER_PICTURE' as const;
export const USER_PICTURE_SUCCESS = 'INFORMATION/USER_PICTURE_SUCCESS' as const;
export const USER_PICTURE_FAILURE = 'INFORMATION/USER_PICTURE_FAILURE' as const;

export const SEARCH_SCHOOL = 'INFORMATION/SEARCH_SCHOOL' as const;
export const SEARCH_SCHOOL_SUCCESS = 'INFORMATION/SEARCH_SCHOOL_SUCCESS' as const;
export const SEARCH_SCHOOL_FAILURE = 'INFORMATION/SEARCH_SCHOOL_FAILURE' as const;
