export const INPUT = 'INFORMATION/INPUT' as const;
export const GENDER = 'INFORMATION/GENDER' as const;
export const BIRTHYEAR = 'INFORMATION/BIRTHYEAR' as const;
export const BIRTHMONTH = 'INFORMATION/BIRTHMONTH' as const;
export const BIRTHDATE = 'INFORMATION/BIRTHDATE' as const;
export const IMAGEURL = 'INFORMATION/IMAGEURL' as const;
export const IMAGEFILE = 'INFORMATION/IMAGEFILE' as const;
export const SCHOOLCODE = 'INFORMATION/SCHOOLCODE' as const;
export const ADDRESS_AND_CODE = 'INFORMATION/ADDRESS_AND_CODE' as const;

export const SEARCH_SCHOOL = 'INFORMATION/SEARCH_SCHOOL' as const;
export const SEARCH_SCHOOL_SUCCESS = 'INFORMATION/SEARCH_SCHOOL_SUCCESS' as const;
export const SEARCH_SCHOOL_FAILURE = 'INFORMATION/SEARCH_SCHOOL_FAILURE' as const;

export const INFORMATION_IMAGE = 'INFORMATION/INFORMATION_IMAGE' as const;
export const INFORMATION_IMAGE_SUCCESS = 'INFORMATION/INFORMATION_IMAGE_SUCCESS' as const;
export const INFORMATION_IMAGE_FAILURE = 'INFORMATION/INFORMATION_IMAGE_FAILURE' as const;

export const ADDRESS = 'INFORMATION/ADDRESS' as const;
export const ADDRESS_SUCCESS = 'INFORMATION/ADDRESS_SUCCESS' as const;
export const ADDRESS_FAILURE = 'INFORMATION/ADDRESS_FAILURE' as const;

export const INFORMATION = 'INFORMATION/INFORMATION' as const;
export const INFORMATION_SUCCESS = 'INFORMATION/INFORMATION_SUCCESS' as const;
export const INFORMATION_FAILURE = 'INFORMATION/INFORMATION_FAILURE' as const;

export const GET_INFORMATION = 'INFORMATION/GET_INFORMATION' as const;
export const GET_INFORMATION_SUCCESS = 'INFORMATION/GET_INFORMATION_SUCCESS' as const;
export const GET_INFORMATION_FAILURE = 'INFORMATION/GET_INFORMATION_FAILURE' as const;

export const AUTOSAVE_INFORMATION = 'INFORMATION/AUTOSAVE_INFORMATION' as const;
export const AUTOSAVE_INFORMATION_SUCCESS = 'INFORMATION/AUTOSAVE_INFORMATION_SUCCESS' as const;
export const AUTOSAVE_INFORMATION_FAILURE = 'INFORMATION/AUTOSAVE_INFORMATION_FAILURE' as const;

export const GEDINFORMATION = 'INFORMATION/GEDINFORMATION' as const;
export const GEDINFORMATION_SUCCESS = 'INFORMATION/GEDINFORMATION_SUCCESS' as const;
export const GEDINFORMATION_FAILURE = 'INFORMATION/GEDINFORMATION_FAILURE' as const;

export const GET_GEDINFORMATION = 'INFORMATION/GET_GEDINFORMATION' as const;
export const GET_GEDINFORMATION_SUCCESS = 'INFORMATION/GET_GEDINFORMATION_SUCCESS' as const;
export const GET_GEDINFORMATION_FAILURE = 'INFORMATION/GET_GEDINFORMATION_FAILURE' as const;

export const AUTOSAVE_GEDINFORMATION = 'INFORMATION/AUTOSAVE_GEDINFORMATION' as const;
export const AUTOSAVE_GEDINFORMATION_SUCCESS = 'INFORMATION/AUTOSAVE_GEDINFORMATION_SUCCESS' as const;
export const AUTOSAVE_GEDINFORMATION_FAILURE = 'INFORMATION/AUTOSAVE_GEDINFORMATION_FAILURE' as const;
