export const GET_PREVIEW = 'PREVIEW/GET_PREVIEW' as const;
export const GET_PREVIEW_SUCCESS = 'PREVIEW/GET_PREVIEW_SUCCESS' as const;
export const GET_PREVIEW_FAILURE = 'PREVIEW/GET_PREVIEW_FAILURE' as const;