export const VERTIFY_CODE = 'resetPassword/VERTIFY_CODE' as const;
export const VERTIFY_PHONE_NUMBER = 'resetPassword/VERTIFY_PHONE_NUMBER' as const;
export const NEW_PASSWORD = 'resetPassword/NEW_PASSWORD' as const;
export const RESET_PASSWORD_ERROR = 'resetPassword/RESET_PASSWORD_ERROR' as const;

export const SEND_RESET_PASSWORD_VERTIFY_CODE = 'resetPassword/SEND_RESET_PASSWORD_VERTIFY_CODE' as const;
export const SEND_RESET_PASSWORD_VERTIFY_CODE_FAILURE = `${SEND_RESET_PASSWORD_VERTIFY_CODE}_FAILURE` as const;
export const SEND_RESET_PASSWORD_VERTIFY_CODE_SUCCESS = `${SEND_RESET_PASSWORD_VERTIFY_CODE}_SUCCESS` as const;

export const CHECK_VERTIFY_CODE = 'resetPassword/CHECK_VERTIFY_CODE' as const;
export const CHECK_VERTIFY_CODE_FAILURE = `${CHECK_VERTIFY_CODE}_FAILURE` as const;
export const CHECK_VERTIFY_CODE_SUCCESS = `${CHECK_VERTIFY_CODE}_SUCCESS` as const;
