export { default as NameColumn } from './NameColumn';
export { default as PhoneNumberColumn } from './PhoneNumberColumn';
export { default as GenderColumn } from './GenderColumn';
export { default as BirthDateColumn } from './BirthDateColumn';
export { default as GradeColumn } from './GradeColumn';
export { default as SchoolNameColumn } from './SchoolNameColumn';
export { default as AddressColumn } from './AddressColumn';
export { default as PictureBtn } from './PictureBtn';
export { default as TotalScoreColumn } from './TotalScoreColumn';
