export const SELF_INTRODUCTION = 'INTRODUCTION/SELF_INTRODUCTION' as const;
export const STUDY_PLAN = 'INTRODUCTION/STUDY_PLAN' as const;

export const SAVE_BOTH = 'INTRODUCTION/SAVE_BOTH' as const;
export const SAVE_BOTH_SUCCESS = 'INTRODUCTION/SAVE_BOTH_SUCCESS' as const;
export const SAVE_BOTH_FAILURE = 'INTRODUCTION/SAVE_BOTH_FAILURE' as const;

export const GET_SELF_INTRODUCTION = 'INTRODUCTION/GET_SELF_INTRODUCTION' as const;
export const GET_STUDY_PLAN = 'INTRODUCTION/GET_STUDY_PLAN' as const;

export const SELF_INTRODUCTION_SUCCESS = 'INTRODUCTION/SELF_INTRODUCTION_SUCCESS' as const;
export const SELF_INTRODUCTION_FAILURE = 'INTRODUCTION/SELF_INTRODUCTION_FAILURE' as const;
export const GET_SELF_INTRODUCTION_SUCCESS = 'INTRODUCTION/GET_SELF_INTRODUCTION_SUCCESS' as const;
export const GET_SELF_INTRODUCTION_FAILURE = 'INTRODUCTION/GET_SELF_INTRODUCTION_FAILURE' as const;

export const STUDY_PLAN_SUCCESS = 'INTRODUCTION/STUDY_PLAN_SUCCESS' as const;
export const STUDY_PLAN_FAILURE = 'INTRODUCTION/STUDY_PLAN_FAILRE' as const;
export const GET_STUDY_PLAN_SUCCESS = 'INTRODUCTION/GET_STUDY_PLAN_SUCCESS' as const;
export const GET_STUDY_PLAN_FAILURE = 'INTRODUCTION/GET_STUDY_PLAN_FAILRE' as const;
