const PHONE_NUMBER = 'user/PHONE_NUMBER' as const;
const NAME = 'user/NAME' as const;
const IS_FINAL_SUBMIT_DONE = 'user/IS_FINAL_SUBMIT_DONE' as const;
const IS_ADMISSION_FEE_PAYED = 'user/IS_ADMISSION_FEE_PAYED' as const;
const IS_RECEIVE_MAIL = 'user/IS_RECEIVE_MAIN' as const;
const SELF_INTRODUCE_LENGTH = 'user/SELF_INTRODUCE_LENGTH' as const;
const STUDY_PLAN_LENGTH = 'user/STUDY_PLAN_LENGTH' as const;
const APPLICATION_TYPE = 'user/APPLICATION_TYPE' as const;
const SUBMIT_TIME = 'user/SUBMIT_TIME' as const;

const GET_USER = 'user/GET_USER' as const;
const GET_USER_FAILURE = `${GET_USER}_FAILURE` as const;
const GET_USER_SUCCESS = `${GET_USER}_SUCCESS` as const;

export {
  PHONE_NUMBER,
  NAME,
  GET_USER,
  IS_FINAL_SUBMIT_DONE,
  IS_ADMISSION_FEE_PAYED,
  IS_RECEIVE_MAIL,
  SELF_INTRODUCE_LENGTH,
  STUDY_PLAN_LENGTH,
  SUBMIT_TIME,
  APPLICATION_TYPE,
  GET_USER_FAILURE,
  GET_USER_SUCCESS,
};
